apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.example.example.com # {"$kpt-set":"version-group"}
spec:
  insecureSkipTLSVerify: true
  group: example.example.com # {"$kpt-set":"group"}
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: apiserver
    namespace: example-system # {"$kpt-set":"namespace"}
  version: v1alpha1
